### ISSUE TITLE
Some methods missing from your Package

### ISSUE THREAD

**Issue by JaganJonnala** [NathanWalker/nativescript-fancyalert#6]
Hey ...Hi 
You have more fancyalert methods which represented as below different scenarios .But from your npm package I got 5 methods .. I need all the methods from your package.. Can you please update what i have to do (I mean I have Missed any scenario).Or are you export those 5 pakcges only..

![image](https://cloud.githubusercontent.com/assets/10844009/20874665/079a7390-bada-11e6-82c1-9f8e37e67127.png)

**Comment by NathanWalker** [comment]
Hi @JaganJonnala go ahead and install the new `1.1.1` version which contains a full list of methods in the published typings. Previously I had a restricted list because the ones above are all that is available on Android, however iOS supports many more. I went ahead and published these additional typings for convenience but keep in mind that the above is all that is available for android at moment. 👍
