### ISSUE TITLE
Not working with Nativescript 6  Android Version

### ISSUE THREAD

**Issue by yonkoGH** [NathanWalker/nativescript-fancyalert#76]
The plugin stop working on android after upgrading the app to Nativescript 6

> "ERROR Error: Uncaught (in promise): Error: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference"

works very will on IOS.

**Comment by OPADA-Eng** [comment]
Same here but without error message.

**Comment by OPADA-Eng** [comment]
@NathanWalker The problem as I see from this instruction:
` var alert = new cn.refactor.lib.colordialog.PromptDialog(app.android.currenntContext);`
if you change it to:
` var alert = new cn.refactor.lib.colordialog.PromptDialog(app.android.foregroundActivity);`
it will work!
because of **currenntContext** is not longer available in the new version of tns-core-modules.

**Comment by OPADA-Eng** [comment]
I submitted a PR #77 if you want to merge.

**Comment by prashantnirgun** [comment]
kindly merge with stable code waiting for update

**Comment by OPADA-Eng** [comment]
Anything to fix this?

**Comment by NathanWalker** [comment]
Fixed in `3.0.9`

**Comment by xubmuajkub** [comment]
After update to `v3.0.9,` it works fine on android but seems like it's not working in iOS. Any solution?
